name: test env

on:
  push:
    branches:
      - main

jobs:
  env-test:
    runs-on: ubuntu-latest
    environment:
      name: TEST
    
    steps:

    - uses: actions/checkout@v2    
      with:
        path: 'repository'
    - name: check base64 files
      env:
        ENV_BASE64: ${{ secrets.ENV_BASE64 }}
      run:
        echo $ENV_BASE64 | base64 --decode >> env.g.dart

    # - uses: britannio/action-install-flutter@v1.1

    # - name: build
    #   run: |
    #     cd repository
    #     flutter pub get
    #     flutter build apk --no-debug --no-profile --release
