name: test env

on:
  push:
    branches:
      - main

jobs:
  env-test:
    runs-on: ubuntu-latest
    environment:
      name: TEST
    
    steps:

    - uses: actions/checkout@v2
      with:
        path: 'repository'
          
    - uses: britannio/action-install-flutter@v1.1

    - name: test env
      run: |
        echo ${{ secrets.TEST1 }}
        echo ${{ vars.TESTA }}

    - name: build
      run: |
        cd repository
        flutter pub get
        flutter pub run build_runner build
        flutter build apk --release
