name: test env

on:
  push:
    branches:
      - main

jobs:
  env-test:
    runs-on: ubuntu-latest
    environment:
      name: TEST
    
    steps:

    - uses: britannio/action-install-flutter@v1.1

    - uses: actions/checkout@v2    
      with:
        path: 'repository'

    - uses: ./repository/.github/workflows/reusable
      with:
        env_secrets: ${{ secrets.ENV_BASE64 }}
        build-target: release-only
